# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcp < Formula
  desc "Run MCP servers without blindly trusting them"
  homepage "https://mcp-hub.info"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_darwin_amd64.tar.gz"
      sha256 "5f1fa54d1e1d4b2e71081146dca59c52d0ab8f3b22510485f5993d5f4419cc2e"

      define_method(:install) do
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_darwin_arm64.tar.gz"
      sha256 "89bffa24ba5111b7a35fedfa8b5678cbcc0334def49776dd885279a724e69c24"

      define_method(:install) do
        bin.install "mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_linux_amd64.tar.gz"
      sha256 "210a968ff81c3d2731dbbf36b20044c6101874aa7894d71856ed1beabba6608a"
      define_method(:install) do
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_linux_arm64.tar.gz"
      sha256 "8171355e43aa778d24c4e5f6cfa6f6f1162cf3ec2f470a27b97883687a644d1e"
      define_method(:install) do
        bin.install "mcp"
      end
    end
  end

  test do
    system "#{bin}/mcp", "--version"
  end
end
