# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcp < Formula
  desc "Run MCP servers without blindly trusting them"
  homepage "https://mcp-hub.info"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_darwin_amd64.tar.gz"
      sha256 "68c150f2aa6d8298dfa8f19d70eb7dcc143ce7765777a42209179c360b94974f"

      define_method(:install) do
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_darwin_arm64.tar.gz"
      sha256 "0527827a682b31bdfad58d46c7c446a9a180b7ad2a69e083c6a038b4d02fa777"

      define_method(:install) do
        bin.install "mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_linux_amd64.tar.gz"
      sha256 "f61f961e94fa2b1f53efa66e651b6f9470f77ce85a5779d01e94194661651b30"
      define_method(:install) do
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.2.0/mcp_0.2.0_linux_arm64.tar.gz"
      sha256 "40c24aea668346a8edbb7e9cfed165c27ef32fbe33d7c45c3df2bd4ae4290bcf"
      define_method(:install) do
        bin.install "mcp"
      end
    end
  end

  test do
    system "#{bin}/mcp", "--version"
  end
end
