# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smcp < Formula
  desc "Run MCP servers without blindly trusting them"
  homepage "https://mcp-hub.info"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.3.0/smcp_0.3.0_darwin_amd64.tar.gz"
      sha256 "3963ff2aaf7b4361cb9295432ed1c9d47d19605e0019217ffb1c455ad35827a5"

      define_method(:install) do
        bin.install "smcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.3.0/smcp_0.3.0_darwin_arm64.tar.gz"
      sha256 "bc5ec68d95e562d1de2523fa76a15dbf3a2d0d58de00b00f44269a42623479ab"

      define_method(:install) do
        bin.install "smcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.3.0/smcp_0.3.0_linux_amd64.tar.gz"
      sha256 "0868fca49d5c1ba9089206f976d832f2e366806e1f81791ac33516c449db6195"
      define_method(:install) do
        bin.install "smcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcp-hub-corp/mcp-client/releases/download/v0.3.0/smcp_0.3.0_linux_arm64.tar.gz"
      sha256 "418192c544236b640f6e8a09c5492057eaf144dcb64cbc67c46d007fabcd0a7f"
      define_method(:install) do
        bin.install "smcp"
      end
    end
  end

  test do
    system "#{bin}/smcp", "--version"
  end
end
